/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.practice.kafka.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5646371994016574953L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"com.practice.kafka.dto\",\"fields\":[{\"name\":\"givenName\",\"type\":\"string\"},{\"name\":\"gender\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"mobileNo\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Employee> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Employee to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Employee from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Employee instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence givenName;
  private java.lang.CharSequence gender;
  private java.lang.CharSequence mobileNo;
  private java.lang.CharSequence email;
  private java.lang.CharSequence country;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param givenName The new value for givenName
   * @param gender The new value for gender
   * @param mobileNo The new value for mobileNo
   * @param email The new value for email
   * @param country The new value for country
   */
  public Employee(java.lang.CharSequence givenName, java.lang.CharSequence gender, java.lang.CharSequence mobileNo, java.lang.CharSequence email, java.lang.CharSequence country) {
    this.givenName = givenName;
    this.gender = gender;
    this.mobileNo = mobileNo;
    this.email = email;
    this.country = country;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return givenName;
    case 1: return gender;
    case 2: return mobileNo;
    case 3: return email;
    case 4: return country;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: givenName = (java.lang.CharSequence)value$; break;
    case 1: gender = (java.lang.CharSequence)value$; break;
    case 2: mobileNo = (java.lang.CharSequence)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: country = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'givenName' field.
   * @return The value of the 'givenName' field.
   */
  public java.lang.CharSequence getGivenName() {
    return givenName;
  }


  /**
   * Sets the value of the 'givenName' field.
   * @param value the value to set.
   */
  public void setGivenName(java.lang.CharSequence value) {
    this.givenName = value;
  }

  /**
   * Gets the value of the 'gender' field.
   * @return The value of the 'gender' field.
   */
  public java.lang.CharSequence getGender() {
    return gender;
  }


  /**
   * Sets the value of the 'gender' field.
   * @param value the value to set.
   */
  public void setGender(java.lang.CharSequence value) {
    this.gender = value;
  }

  /**
   * Gets the value of the 'mobileNo' field.
   * @return The value of the 'mobileNo' field.
   */
  public java.lang.CharSequence getMobileNo() {
    return mobileNo;
  }


  /**
   * Sets the value of the 'mobileNo' field.
   * @param value the value to set.
   */
  public void setMobileNo(java.lang.CharSequence value) {
    this.mobileNo = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static com.practice.kafka.dto.Employee.Builder newBuilder() {
    return new com.practice.kafka.dto.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.practice.kafka.dto.Employee.Builder newBuilder(com.practice.kafka.dto.Employee.Builder other) {
    if (other == null) {
      return new com.practice.kafka.dto.Employee.Builder();
    } else {
      return new com.practice.kafka.dto.Employee.Builder(other);
    }
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.practice.kafka.dto.Employee.Builder newBuilder(com.practice.kafka.dto.Employee other) {
    if (other == null) {
      return new com.practice.kafka.dto.Employee.Builder();
    } else {
      return new com.practice.kafka.dto.Employee.Builder(other);
    }
  }

  /**
   * RecordBuilder for Employee instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private java.lang.CharSequence givenName;
    private java.lang.CharSequence gender;
    private java.lang.CharSequence mobileNo;
    private java.lang.CharSequence email;
    private java.lang.CharSequence country;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.practice.kafka.dto.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.givenName)) {
        this.givenName = data().deepCopy(fields()[0].schema(), other.givenName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.gender)) {
        this.gender = data().deepCopy(fields()[1].schema(), other.gender);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.mobileNo)) {
        this.mobileNo = data().deepCopy(fields()[2].schema(), other.mobileNo);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.country)) {
        this.country = data().deepCopy(fields()[4].schema(), other.country);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(com.practice.kafka.dto.Employee other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.givenName)) {
        this.givenName = data().deepCopy(fields()[0].schema(), other.givenName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.gender)) {
        this.gender = data().deepCopy(fields()[1].schema(), other.gender);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.mobileNo)) {
        this.mobileNo = data().deepCopy(fields()[2].schema(), other.mobileNo);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.country)) {
        this.country = data().deepCopy(fields()[4].schema(), other.country);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'givenName' field.
      * @return The value.
      */
    public java.lang.CharSequence getGivenName() {
      return givenName;
    }


    /**
      * Sets the value of the 'givenName' field.
      * @param value The value of 'givenName'.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder setGivenName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.givenName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'givenName' field has been set.
      * @return True if the 'givenName' field has been set, false otherwise.
      */
    public boolean hasGivenName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'givenName' field.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder clearGivenName() {
      givenName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gender' field.
      * @return The value.
      */
    public java.lang.CharSequence getGender() {
      return gender;
    }


    /**
      * Sets the value of the 'gender' field.
      * @param value The value of 'gender'.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder setGender(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.gender = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gender' field has been set.
      * @return True if the 'gender' field has been set, false otherwise.
      */
    public boolean hasGender() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'gender' field.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder clearGender() {
      gender = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'mobileNo' field.
      * @return The value.
      */
    public java.lang.CharSequence getMobileNo() {
      return mobileNo;
    }


    /**
      * Sets the value of the 'mobileNo' field.
      * @param value The value of 'mobileNo'.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder setMobileNo(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.mobileNo = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'mobileNo' field has been set.
      * @return True if the 'mobileNo' field has been set, false otherwise.
      */
    public boolean hasMobileNo() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'mobileNo' field.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder clearMobileNo() {
      mobileNo = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.country = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.practice.kafka.dto.Employee.Builder clearCountry() {
      country = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.givenName = fieldSetFlags()[0] ? this.givenName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.gender = fieldSetFlags()[1] ? this.gender : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.mobileNo = fieldSetFlags()[2] ? this.mobileNo : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.country = fieldSetFlags()[4] ? this.country : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.givenName);

    out.writeString(this.gender);

    out.writeString(this.mobileNo);

    out.writeString(this.email);

    out.writeString(this.country);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.givenName = in.readString(this.givenName instanceof Utf8 ? (Utf8)this.givenName : null);

      this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);

      this.mobileNo = in.readString(this.mobileNo instanceof Utf8 ? (Utf8)this.mobileNo : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.givenName = in.readString(this.givenName instanceof Utf8 ? (Utf8)this.givenName : null);
          break;

        case 1:
          this.gender = in.readString(this.gender instanceof Utf8 ? (Utf8)this.gender : null);
          break;

        case 2:
          this.mobileNo = in.readString(this.mobileNo instanceof Utf8 ? (Utf8)this.mobileNo : null);
          break;

        case 3:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 4:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










